name: Release Master

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and release latest image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      -
        name: Docker login
        run: docker login -u "${{ secrets.QUAY_IO_USER }}" -p "${{ secrets.QUAY_IO_TOKEN }}" quay.io
      -
        name: Run GoReleaser
        run: curl -sL https://git.io/goreleaser | bash -s -- -f build/ci/.goreleaser.yml --snapshot --skip-publish --rm-dist && docker push "quay.io/bertpersyn/kube-httpcache:latest"
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_USER_TOKEN }}